# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ilmoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_ilmoapp.question_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='title',
        ),
        migrations.AddField(
            model_name='questionform',
            name='questions',
            field=models.ManyToManyField(to='ilmoapp.Question'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ilmoapp.Question'),
            preserve_default=False,
        ),
    ]
