# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0003_auto_20160205_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionform',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
