# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0005_auto_20160205_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ilmoapp.Questionnaire'),
            preserve_default=False,
        ),
    ]
