# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0006_auto_20160205_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectonequestion',
            old_name='answer',
            new_name='select_one',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
