# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0007_auto_20160205_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='max_length',
            field=models.IntegerField(default=1000),
        ),
    ]
