# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 18:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0008_textquestion_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('questionnaire_title', models.CharField(max_length=100)),
                ('questionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ilmoapp.Questionnaire')),
            ],
        ),
    ]
