# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0009_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(to='ilmoapp.Question'),
        ),
    ]
