# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0010_auto_20160205_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectonequestion',
            name='select_one',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
