# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 21:30
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0011_auto_20160205_2124'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='questionnaire',
            name='questions',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='ilmoapp.Question'),
        ),
    ]
