# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoapp', '0013_questionnaire_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='selectonequestion',
            name='options',
            field=models.ManyToManyField(to='ilmoapp.SelectOption'),
        ),
    ]
